export function getUiElements() {
  return {
    focusHint: document.querySelector("#focus-hint"),
    titleScreen: document.querySelector("#title-screen"),
    continueButton: document.querySelector("#continue-button"),
    newGameButton: document.querySelector("#new-game-button"),
    pauseMenu: document.querySelector("#pause-menu"),
    resumeButton: document.querySelector("#resume-button"),
    restartRunButton: document.querySelector("#restart-run-button"),
    returnTitleButton: document.querySelector("#return-title-button"),
    objectivePanel: document.querySelector("#objective-panel"),
    objectiveText: document.querySelector("#objective-text"),
    chapterCard: document.querySelector("#chapter-card"),
    chapterCardTitle: document.querySelector("#chapter-card-title"),
    chapterCardSubtitle: document.querySelector("#chapter-card-subtitle"),
    interactionPrompt: document.querySelector("#interaction-prompt"),
    dialogue: document.querySelector("#dialogue"),
    speaker: document.querySelector("#dialogue-speaker"),
    line: document.querySelector("#dialogue-line"),
    choiceA: document.querySelector("#choice-a"),
    choiceB: document.querySelector("#choice-b"),
    ending: document.querySelector("#ending"),
    endingTitle: document.querySelector("#ending-title"),
    endingLineA: document.querySelector("#ending-line-a"),
    endingLineB: document.querySelector("#ending-line-b"),
    restartButton: document.querySelector("#restart-button"),
    endingReturnButton: document.querySelector("#ending-return-button"),
    transition: document.querySelector("#transition-overlay"),
  };
}